# Use an official Node runtime as a parent image
FROM node:21

# Set the working directory in the container
WORKDIR /app/frontend

# Install frontend dependencies
COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm install
COPY ./frontend ./

# Expose port for React development server
EXPOSE 3000

# Run React development server when the container launches
CMD ["npm", "start"]